### ISSUE TITLE
About the parameter  'overlap'

### ISSUE THREAD

**Issue by wj320** [Zhaoyi-Yan/Shift-Net_pytorch#125]
Thanks for sharing your code!
I have a question about the parameter 'overlap'. I download your pretrained model and test it on CelebA-HQ dataset  with rectangle mask.  When I set '--overlap 4', the results are pretty good; however, when I set '--overlap 
 0', the output images are very poor. Why is it that?

**Comment by Zhaoyi-Yan** [comment]
1. `--overlap` is just used to be consistent with the settings with Context-Encoders and High-Resolution. The authors adopt the central mask with size (128-4)*(128-4), so we follow the settings just to make comparisons easily.

2.  When the model is trained with a fixed mask, then we must adopt the same mask, so the performance degrades severely.  It is because the model is not trained with masks of other sizes. When the training is with random masks( irregular masks or rectangle masks with random positions), then the model performs well with any masks in testing.  I have described this phenomenon in Readme#Masks.

**Comment by wj320** [comment]
Thanks for your reply : ) !!!
